import type { Metadata } from "next";
import { Lexend_Deca } from "next/font/google";
import { ClerkProvider } from '@clerk/nextjs';
import { dark } from '@clerk/themes';
import "./globals.css";

const lexend = Lexend_Deca({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Filmbox",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/favicon.ico",
        href: "/favicon.ico",
      }
    ],
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{ 
        baseTheme: dark
      }}
    >
      <html lang="en">
        <body className={lexend.className}>{children}</body>
      </html>
    </ClerkProvider>
  );
}
